### ISSUE TITLE
Social Network Links - (Must Have)

### ISSUE THREAD

**Issue by Joao4569** [Joao4569/lovin_summer#21]
EPIC: UX and Design

As a **User** I can **find social links such as facebook, instagram** so that **I may connect socially with the organisation**.

**Acceptance Criteria**
- [x] links should open in a new tab 
- [x] links are manually tested and validated
- [x] Responsive design
- [x] User story moved to Done Column.

**Tasks**
- [x] Create links for social sites on each page
