### ISSUE TITLE
Events Calendar - (Won't Have)

### ISSUE THREAD

**Issue by Joao4569** [Joao4569/lovin_summer#25]
EPIC: Features

As a **Provider** I can **easily display a series of events** so that **I can promote said events among the users.**

**Acceptance Criteria**
- [ ] Cards should be equally sized.
- [ ] Information displayed should be clear and well formatted
- [ ] Details to be included are: Date, Venue, Description
- [ ] Cards layout needs to be responsive from mobile to large-screen (1200px+)
- [ ] The ratio of image/card area to be fixed and maintained throughout
- [ ] User story moved to Done column

**Tasks**
- [ ] Create bootstrap cards
- [ ] Add images, info and dates about the events in the cards
- [ ] Make these cards responsive (user might also want to plan the outings from a laptop/desktop)
