### ISSUE TITLE
Gallery - (Won't Have)

### ISSUE THREAD

**Issue by Joao4569** [Joao4569/lovin_summer#26]
EPIC: Features

As a **User** I can **have a look at the images of the places worth to see** so that **I can pick up some the most popular attractions.**

**Acceptance Criteria**
- [ ] Images are of suitable size and quality
- [ ] Respnosive design
- [ ] User story moved to Done Column

**Tasks**
- [ ] Search creative commons to find suitable images
- [ ] Create a gallery grid
- [ ] Add images to the grid
