### ISSUE TITLE
Sign-up Form - (Should Have)

### ISSUE THREAD

**Issue by Joao4569** [Joao4569/lovin_summer#27]
EPIC: Features

As a **User** I can **fill out the form to request further inforation or sign up for newsletters** so that **I can get infomation about future events or popular attractions in my area.**

**Acceptance Criteria**
- [x] Input data is validated before submission
- [x] Submit button is manually tested
- [x] Form return thank you message.
- [x] Responsive design.
- [x] User story moved to Done column.

**Tasks**
- [x] Create online form to collect user contact details
- [x] Validate user input.
- [x] Create thank you note after submitting.

**Comment by ObiOne84** [comment]
The contact form is done, and thank you note as well. I tried to use the button to get thank you note to appear once the form is submitted, but it doesn't work. It keeps directing me to the home page. I also used input type=submit, but nothing seems to work. Not sure what is wrong there. Thanks
