### ISSUE TITLE
Weather Info - (Won't Have)

### ISSUE THREAD

**Issue by Joao4569** [Joao4569/lovin_summer#28]
EPIC: API Requests

As a **Provider** I can **access weather API** so that **I can provide current and forecast weather conditions**

**Acceptance Criteria**
- [ ] A symbol for weather and digits for temperature are displayed next to the map with the legend: "Current weather in your location: XYZ".
- [ ] A symbol and digits for temperature are displayed next to the date in the events cards (no legend required) for latest forecasted weather at the location.
- [ ] User story moved to the Done column

**Tasks**
- [ ] Fetch data from appointed API.
- [ ] Display data alongside the map and the events cards
- [ ] Handle errors
