### ISSUE TITLE
Create Homepage - (Must Have)

### ISSUE THREAD

**Issue by Joao4569** [Joao4569/lovin_summer#29]
EPIC: UX and Design

As a **User,** I can **access the homepage first** so that **I can be introduced to the site.**

**Acceptance Criteria**
- [x] Have a Navigation Bar on the page
- [x] Have a hero section an image with welcome text and a footer
- [x] Page manually tested, all links working
- [x] Responsive - Mobile first
- [x] Tasks moved to the done column on the Kanban board

**Tasks**
- [x] Create site header
- [x] Create Hero section content
- [x] Create a video section and map link image
- [x] Create a Footer with social links and partner links
- [x] Add content to promote wellness of being outdoors
