### ISSUE TITLE
Favourited Activities - (Must Have)

### ISSUE THREAD

**Issue by Joao4569** [Joao4569/lovin_summer#30]
EPIC: Features

As a **User,** I can **select "favourite" activities** so that **I can keep a log and filter by my selected favourite choices.**

**Acceptance Criteria**
- [x] Toggle favourites Button works as intended and displays UI changes to user
- [x] Data is persisted in a database
- [x] No data is mutated or duplicated
- [x] User story moved to the Done column

**Tasks**
- [x] Create like and unlike button
- [x] Create toggle favourite function
- [x] Store data on server/local storage so information persists
