### ISSUE TITLE
Filter/Sort Activities - (Must Have)

### ISSUE THREAD

**Issue by Joao4569** [Joao4569/lovin_summer#31]
EPIC: Features

As a **User,** I can **filter/sort activities** so that **I can quickly access information about my favourite options.**

**Acceptance Criteria**
- [x] Users can sort by geographical radius/ favourites/ tags
- [x] Input field allows user to filter clearly defined tags
- [x] Input radius distance filter is clearly defined when active
- [x] Filter by favourites button is clearly defined when active
- [x] All information is displayed in an easy to read format
- [x] User story moved to the Done column

**Tasks**
- [x] Create a filter by tags selection input
- [x] Render filtered results to the user in a clear manner
- [x] Allow sorting based on location distance from user
- [x] Create Sort by favourites button
