### ISSUE TITLE
Site navigation - (Must Have)

### ISSUE THREAD

**Issue by Joao4569** [Joao4569/lovin_summer#4]
EPIC: UX and design

As a **User** I can **easily navigate between the sites pages** so that **I can find what I am looking for**.

**Acceptance Criteria**
- [x] Uniform navigation tabs on each page of site
- [x] All navigation links manually tested for each page and working as intended
- [x] Tasks moved to done column on Kanban board

**Tasks**
- [x] Create Navigation tabs for site header
- [x] Create links for navigation tabs on each page
