### ISSUE TITLE
Interactive Map - (Must Have)

### ISSUE THREAD

**Issue by DarrachBarneveld** [Joao4569/lovin_summer#5]
EPIC: Map

As a **User** I can **easily navigate between the sites pages** so that **I can find what I am looking for.**

**Acceptance Criteria**
- [x] Map UI created and functioning as intended
- [x] Map markers working as intended and displaying on map
- [x] Map animations working as intended
- [x] Map is responsive
- [x] Map functionality tested
- [x] User Story moved to Done Column

**Tasks**
- [x] Map UI
- [x] Map Markers
- [x] Map Animations
