### ISSUE TITLE
User Location - (Must Have)

### ISSUE THREAD

**Issue by DarrachBarneveld** [Joao4569/lovin_summer#6]
EPIC: Geolocation

As a **User** I can **easily find my current location** so that **I can find potential events near me.**

**Acceptance Criteria**
- [x] User marker working as intended and displaying on map
- [x] Markers of nearby events showing on the map
- [x] Nearby Activty Information rendered in side HUD
- [x] User Story moved to Done Column

**Tasks**
- [x] User Location Marker
- [x] Marker of nearby events
- [x] Render event info in HUD
