### ISSUE TITLE
Easter egg - (Could Have)

### ISSUE THREAD

**Issue by jbocciadev** [Joao4569/lovin_summer#67]
EPIC: User experience

**As a Provider**, I can **provide an extra feature** so that **I can appeal to the emotional side of the user's memories**

**Acceptance Criteria**
- [x] A hyperlink is displayed in the footer that takes the user to a youtube video.
- [x] the video opens in a new tab

**Tasks**
- [x] Create hyperling to youtube video.
