### ISSUE TITLE
Site Data - (Must Have)

### ISSUE THREAD

**Issue by DarrachBarneveld** [Joao4569/lovin_summer#7]
EPIC: API Requests

As a **User** I can **get current, accurate information about events** so that **I can find their location, website and contact information.**

**Acceptance Criteria**
- [x] Fetching API information works as intended
- [x] Data is manipulated and displayed in a clear and legible format for the user
- [x] Loading animations are set
- [x] Any potential errors are handled and the user is informed
- [x] User story moved to Done Column

**Tasks**
- [x] Fetch data from appointed API
- [x] Modifiy and render data for display
- [x] Display pleasant loading UI for user
- [x] Handle any errors and display error message to user
