### ISSUE TITLE
QR Code - (Could Have)

### ISSUE THREAD

**Issue by jbocciadev** [Joao4569/lovin_summer#74]
EPIC: User experience

As a **Provider** I can **present a QR code** so that **potential users can access the website using the camera on their phone "on the go"**.

**Acceptance Criteria**
- [x] A QR code is developed that targets the website.
- [x] The QR code uses the page's logo.
- [x] User story is moved to the Done column.

**Tasks**
- [x] Create QR code
- [x] Display QR code in readme including the site used for generating it.
